channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - packaging==23.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.11.3
name: mlflow-env
